customhost = "employee-data.cmxl9i4rf9tv.us-east-2.rds.amazonaws.com"
customuser = "techguru"
custompass = "techguru2023"
customdb = "employee-data"
custombucket = "addemployeeee"
customregion = "us-east-2"
